/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package conflictmgmt;

public class App {
    public String getGreeting() {
        return "Bonjour Monde";
    }

    public String anotherGreeting() {
        return "Hello World2";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
